import { financeEntries, healthEntries, memoryItems } from './shaikh-os-memory';
import { listGoogleAccounts, listGoogleIntelligence } from './google-integrations';
import { listLatestGitHubIssues, listRepositoryCommits, listRepositoryIssues } from './github-integration';
import { getVercelDeploymentIntelligence, type VercelDeploymentSummary } from './vercel-integration';

export type AuditMetric = { label: string; value: number | string; detail: string; severity?: 'good' | 'warning' | 'bad' };
export type EvidenceMetric = { label: string; value: number | string; total?: number; detail: string; severity?: 'good' | 'warning' | 'bad' };
export type SystemWeakness = { id: string; title: string; detail: string; evidence: string[]; metrics: EvidenceMetric[]; confidenceScore: number; reasoningChain: string[]; severity: 'low' | 'medium' | 'high' };
export type EngineeringPlan = { complexity: 'low' | 'medium' | 'high'; affectedFiles: string[]; estimatedEffort: string; implementationSteps: string[]; databaseChanges: string[]; uiChanges: string[]; testingRequirements: string[] };
export type PromptHistoryItem = { generatedAt: string; prompt: string; source: 'deterministic' | 'premium-model' };
export type ExecutionStatus = 'Proposed' | 'Approved' | 'Issue Created' | 'Prompt Generated' | 'In Development' | 'Testing' | 'Deployed';
export type ImprovementProposal = { id: string; observation: string; problem: string; evidence: string[]; metrics: EvidenceMetric[]; confidenceScore: number; reasoningChain: string[]; recommendation: string; expectedImpact: string; riskLevel: 'low' | 'medium' | 'high'; complexity: 'low' | 'medium' | 'high'; engineeringPlan: EngineeringPlan; codexPrompt: string; promptHistory: PromptHistoryItem[]; executionStatus: ExecutionStatus; status: 'later' | 'useful' | 'not_useful' | 'approved' };
export type SystemAuditSnapshot = { capturedAt: string; metrics: AuditMetric[]; emptySections: string[]; stalePages: string[]; failedSyncDiagnostics: string[]; commandParsingConfidenceAverage: number | null; clarificationCount: number; cancelledPlansCount: number; weaknesses: SystemWeakness[]; proposals: ImprovementProposal[]; statusBoard: Record<ExecutionStatus, number>; githubIntelligence: Awaited<ReturnType<typeof buildGitHubIntelligence>>; vercel: VercelDeploymentSummary };

type UnknownRecord = Record<string, unknown>;
const statuses: ExecutionStatus[] = ['Proposed', 'Approved', 'Issue Created', 'Prompt Generated', 'In Development', 'Testing', 'Deployed'];

function supabaseConfig() { const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url: url.replace(/\/$/, ''), key } : null; }
async function supabaseRequest<T>(path: string, init: RequestInit = {}) { const config = supabaseConfig(); if (!config) return null; const response = await fetch(`${config.url}/rest/v1/${path}`, { ...init, headers: { apikey: config.key, Authorization: `Bearer ${config.key}`, 'Content-Type': 'application/json', Prefer: 'return=representation', ...(init.headers || {}) }, cache: 'no-store' }); if (!response.ok) return null; if (response.status === 204) return null; return response.json() as Promise<T>; }

export async function buildSystemAuditSnapshot(): Promise<SystemAuditSnapshot> {
  const [googleAccounts, google, persistedFeedback, actionPlans, reasoningLogs, storedProposals, githubIntelligence, vercel] = await Promise.all([
    listGoogleAccounts().catch(() => []),
    listGoogleIntelligence().catch(() => ({ gmailSignals: [], driveSignals: [], contactCandidates: [], knowledgeGraph: { entities: [], signals: [], needsReview: [], projectLinks: {} } })),
    supabaseRequest<UnknownRecord[]>('agent_feedback?select=feedback_type,raw_feedback,created_at&order=created_at.desc&limit=200'),
    supabaseRequest<UnknownRecord[]>('agent_action_plans?select=status,confidence,action_type,created_at&order=created_at.desc&limit=200'),
    supabaseRequest<UnknownRecord[]>('agent_reasoning_logs?select=confidence,created_at&order=created_at.desc&limit=200'),
    supabaseRequest<UnknownRecord[]>('agent_improvement_proposals?select=proposal_key,status,execution_status,github_issue_number,codex_prompt,updated_at&order=updated_at.desc&limit=200'),
    buildGitHubIntelligence(),
    getVercelDeploymentIntelligence().catch((error) => ({ configured: Boolean(process.env.VERCEL_TOKEN), deployments: [], productionUrl: null, latestStatus: 'unavailable', failedDeployments: [], error: error instanceof Error ? error.message : 'Vercel unavailable' })),
  ]);

  const projects = new Set(memoryItems.map((item) => item.project).filter((project) => project !== 'General'));
  const openTasks = memoryItems.filter((item) => item.intent === 'task');
  const notes = memoryItems.filter((item) => item.intent === 'note' || item.intent === 'idea' || item.intent === 'decision');
  const failedLogs = googleAccounts.flatMap((account) => account.sync_logs.filter((log) => log.status !== 'success'));
  const failedSyncDiagnostics = failedLogs.map((log) => `${log.sync_type}: ${log.message ?? log.error_code ?? 'failed'}${log.missing_scope ? ` (missing ${log.missing_scope})` : ''}`).slice(0, 8);
  const confidenceValues = [...(reasoningLogs ?? []), ...(actionPlans ?? [])].map((row) => typeof row.confidence === 'number' ? row.confidence : null).filter((value): value is number => value !== null);
  const commandParsingConfidenceAverage = confidenceValues.length ? Number((confidenceValues.reduce((sum, value) => sum + value, 0) / confidenceValues.length).toFixed(3)) : null;
  const clarificationCount = (actionPlans ?? []).filter((row) => row.action_type === 'ask_clarification' || row.status === 'clarification').length;
  const cancelledPlansCount = (actionPlans ?? []).filter((row) => String(row.status ?? '').match(/cancel/)).length + (persistedFeedback ?? []).filter((row) => String(row.feedback_type ?? row.raw_feedback ?? '').match(/cancel|not_useful/)).length;
  const emptySections = [openTasks.length ? null : 'Open tasks', notes.length ? null : 'Notes/decisions', healthEntries.length ? null : 'Health logs', financeEntries.length ? null : 'Finance logs', googleAccounts.length ? null : 'Connected Google accounts', google.knowledgeGraph.signals.length ? null : 'Google knowledge signals'].filter(Boolean) as string[];
  const stalePages = memoryItems.filter((item) => (Date.now() - new Date(item.createdAt).getTime()) / 86400000 > 14).map((item) => `${item.project}: ${item.title}`).slice(0, 8);
  const weaknesses = detectWeaknesses({ emptySections, failedSyncDiagnostics, commandParsingConfidenceAverage, clarificationCount, cancelledPlansCount, googleSignals: google.knowledgeGraph.signals.length, linkedGoogleSignals: Object.values(google.knowledgeGraph.projectLinks).flat().filter((signal) => signal.project !== 'Needs Review').length, healthStructuredFields: healthEntries, memoryCount: memoryItems.length });
  const proposals = mergeStoredState(await generateImprovementProposals(weaknesses), storedProposals ?? [], githubIntelligence.latestIssues);
  const statusBoard = statuses.reduce((acc, status) => ({ ...acc, [status]: proposals.filter((proposal) => proposal.executionStatus === status).length }), {} as Record<ExecutionStatus, number>);

  return { capturedAt: new Date().toISOString(), metrics: [
    { label: 'Detected weaknesses', value: weaknesses.length, detail: 'Evidence-based rules triggered in this audit' },
    { label: 'Open GitHub issues', value: githubIntelligence.openIssues.length, detail: 'Read-only GitHub repository intelligence' },
    { label: 'Generated prompts', value: proposals.filter((proposal) => proposal.codexPrompt).length, detail: 'Stored for human-approved Codex execution only' },
    { label: 'Latest deployment', value: vercel.latestStatus, detail: vercel.productionUrl ?? 'Vercel read-only status' },
    { label: 'Total projects', value: projects.size, detail: 'From current Shaikh OS memory items' },
    { label: 'Health logs', value: healthEntries.length, detail: 'Structured health entries available' },
    { label: 'Avg parse confidence', value: commandParsingConfidenceAverage ?? 'Unavailable', detail: confidenceValues.length ? `${confidenceValues.length} reasoning/action records` : 'No persisted confidence history yet' },
    { label: 'Cancelled plans', value: cancelledPlansCount, detail: 'Cancelled or not-useful feedback signals' },
  ], emptySections, stalePages, failedSyncDiagnostics, commandParsingConfidenceAverage, clarificationCount, cancelledPlansCount, weaknesses, proposals, statusBoard, githubIntelligence, vercel };
}

function pct(part: number, total: number) { return total ? Math.round((part / total) * 100) : 0; }
function detectWeaknesses(input: { emptySections: string[]; failedSyncDiagnostics: string[]; commandParsingConfidenceAverage: number | null; clarificationCount: number; cancelledPlansCount: number; googleSignals: number; linkedGoogleSignals: number; healthStructuredFields: unknown[]; memoryCount: number }): SystemWeakness[] {
  const weaknesses: SystemWeakness[] = [];
  const push = (weakness: SystemWeakness) => weaknesses.push(weakness);
  if (input.emptySections.length) push({ id: 'empty-sections', title: 'Sections with no real data', detail: 'Some OS sections are empty and should say so plainly instead of showing filler.', evidence: input.emptySections, metrics: [{ label: 'Empty sections', value: input.emptySections.length, total: 6, detail: `${input.emptySections.length}/6 audited sections are empty`, severity: 'warning' }], confidenceScore: 88, reasoningChain: ['Empty-state audit found sections with zero records.', 'Showing filler would reduce operator trust.', 'Explicit empty states preserve evidence integrity.'], severity: 'medium' });
  if (input.failedSyncDiagnostics.length >= 2) push({ id: 'repeated-sync-failures', title: 'Repeated failed sync', detail: 'Google sync errors need grouped diagnostics and recovery guidance.', evidence: input.failedSyncDiagnostics, metrics: [{ label: 'Failed sync diagnostics', value: input.failedSyncDiagnostics.length, detail: `${input.failedSyncDiagnostics.length} recent failed Google sync log(s)`, severity: 'bad' }], confidenceScore: 92, reasoningChain: ['Multiple sync failures indicate a repeated integration problem.', 'Ungrouped errors slow human recovery.', 'A recovery queue should explain account, service, missing scope, and next action.'], severity: 'high' });
  if (input.commandParsingConfidenceAverage !== null && input.commandParsingConfidenceAverage < 0.72) push({ id: 'low-command-confidence', title: 'Low confidence command parses', detail: 'Average parser confidence is below the safe execution threshold.', evidence: [`Average parse confidence: ${input.commandParsingConfidenceAverage}`], metrics: [{ label: 'Avg parse confidence', value: input.commandParsingConfidenceAverage, detail: 'Below safe threshold 0.72', severity: 'bad' }], confidenceScore: 90, reasoningChain: ['Low parse confidence increases wrong-plan risk.', 'Autonomous execution remains blocked by safety policy.', 'More examples and stricter clarification gates improve safety.'], severity: 'high' });
  if (input.cancelledPlansCount > 3) push({ id: 'too-many-cancellations', title: 'Too many cancelled confirmations', detail: 'Users are rejecting proposed plans often enough to tune proposal quality.', evidence: [`Cancelled or not useful: ${input.cancelledPlansCount}`], metrics: [{ label: 'Cancelled plans', value: input.cancelledPlansCount, detail: 'Cancellation threshold is 3', severity: 'warning' }], confidenceScore: 84, reasoningChain: ['Repeated rejection is a direct quality signal.', 'Capturing reason categories enables targeted prompt improvements.', 'Trend charts can verify whether changes help.'], severity: 'medium' });
  const healthText = JSON.stringify(input.healthStructuredFields); const missing = ['severity', 'duration', 'trigger', 'medication'].filter((field) => !healthText.match(new RegExp(field, 'i')));
  if (input.healthStructuredFields.length && missing.length) push({ id: 'health-structure', title: 'Health logs not structured enough', detail: 'Health records track basics but miss fields needed for trend analysis.', evidence: [`Health logs analyzed: ${input.healthStructuredFields.length}`, `Missing fields: ${missing.join(', ')}`], metrics: missing.map((field) => ({ label: `Missing ${field}`, value: input.healthStructuredFields.length, total: input.healthStructuredFields.length, detail: `${input.healthStructuredFields.length}/${input.healthStructuredFields.length} logs lack ${field}`, severity: 'warning' as const })), confidenceScore: 94, reasoningChain: ['Health entries exist, so field completeness can be measured.', 'Missing severity/duration/trigger/medication blocks trend analysis.', 'Adding structured fields improves future recommendations without executing medical actions.'], severity: 'medium' });
  if (input.googleSignals && input.linkedGoogleSignals < input.googleSignals) push({ id: 'google-project-links', title: 'Google signals not linked to projects', detail: 'Some Google signals remain unlinked or in review, reducing project context.', evidence: [`Linked ${input.linkedGoogleSignals} of ${input.googleSignals}`], metrics: [{ label: 'Linked Google signals', value: `${pct(input.linkedGoogleSignals, input.googleSignals)}%`, total: input.googleSignals, detail: `${input.linkedGoogleSignals}/${input.googleSignals} signals linked`, severity: 'warning' }], confidenceScore: 87, reasoningChain: ['Unlinked Google signals cannot reliably support project memory.', 'A review queue is safer than auto-linking.', 'Human correction data can train future suggestions.'], severity: 'medium' });
  if (input.memoryCount > 0) push({ id: 'static-memory-risk', title: 'Static metrics still present', detail: 'Some snapshot data comes from local memory arrays, so the UI should label it as current stored memory instead of live database totals.', evidence: ['memoryItems, healthEntries, financeEntries are local records'], metrics: [{ label: 'Local memory records', value: input.memoryCount, detail: 'Seed/stored memory arrays included in audit', severity: 'warning' }], confidenceScore: 80, reasoningChain: ['Local arrays are useful but not live telemetry.', 'Unlabeled static counts can be mistaken for current production totals.', 'Labels or persisted counts reduce ambiguity.'], severity: 'low' });
  return weaknesses;
}

async function generateImprovementProposals(weaknesses: SystemWeakness[]): Promise<ImprovementProposal[]> { return weaknesses.map((weakness) => proposalFromWeakness(weakness, 'deterministic')); }
function proposalFromWeakness(weakness: SystemWeakness, source: 'deterministic' | 'premium-model'): ImprovementProposal { const engineeringPlan = planFor(weakness); const codexPrompt = buildCodexPrompt(weakness, engineeringPlan); return { id: weakness.id, observation: weakness.title, problem: weakness.detail, evidence: weakness.evidence, metrics: weakness.metrics, confidenceScore: weakness.confidenceScore, reasoningChain: weakness.reasoningChain, recommendation: recommendationFor(weakness.id), expectedImpact: impactFor(weakness.severity), riskLevel: weakness.severity === 'high' ? 'medium' : 'low', complexity: engineeringPlan.complexity, engineeringPlan, codexPrompt, promptHistory: [{ generatedAt: new Date().toISOString(), prompt: codexPrompt, source }], executionStatus: 'Prompt Generated', status: 'later' }; }
function planFor(weakness: SystemWeakness): EngineeringPlan { const map: Record<string, Partial<EngineeringPlan>> = { 'repeated-sync-failures': { complexity: 'medium', affectedFiles: ['lib/google-integrations.ts', 'app/os/improve/page.tsx'], estimatedEffort: '1-2 days' }, 'health-structure': { complexity: 'medium', affectedFiles: ['lib/shaikh-os-memory.ts', 'app/os/health/page.tsx', 'supabase/migrations/*'], estimatedEffort: '1-2 days', databaseChanges: ['Add optional health severity, duration, trigger, medication, follow-up fields.'] }, 'google-project-links': { complexity: 'medium', affectedFiles: ['lib/google-integrations.ts', 'app/os/sources/page.tsx'], estimatedEffort: '1-2 days' } }; const base = map[weakness.id] ?? {}; return { complexity: base.complexity ?? 'low', affectedFiles: base.affectedFiles ?? ['lib/shaikh-os-improvement.ts', 'app/os/improve/page.tsx'], estimatedEffort: base.estimatedEffort ?? '0.5-1 day', implementationSteps: ['Confirm the issue and acceptance criteria with a human reviewer.', 'Update only the affected files listed in this plan.', 'Add or update persistence using additive migrations only when needed.', 'Run build and targeted checks.', 'Wait for human approval before merge or deployment.'], databaseChanges: base.databaseChanges ?? ['No destructive database changes. Use additive migrations only if persistence is needed.'], uiChanges: ['Expose evidence, metrics, confidence, status, and human approval controls.'], testingRequirements: ['Run npm run build.', 'Verify no automatic code modification, merge, deployment, or environment mutation is introduced.'] }; }
function mergeStoredState(proposals: ImprovementProposal[], stored: UnknownRecord[], issues: { source_id?: string; github_issue_number?: number; github_issue_url?: string; status?: string }[]) { return proposals.map((proposal) => { const row = stored.find((item) => item.proposal_key === proposal.id); const issue = issues.find((item) => item.source_id === proposal.id); const approved = row?.status === 'approved'; return { ...proposal, status: (row?.status as ImprovementProposal['status']) ?? proposal.status, executionStatus: issue ? 'Issue Created' : approved ? 'Approved' : proposal.executionStatus, codexPrompt: String(row?.codex_prompt ?? proposal.codexPrompt) }; }); }
async function buildGitHubIntelligence() { const [latestIssues, openIssues, closedIssues, recentCommits] = await Promise.all([listLatestGitHubIssues(20).catch(() => []), listRepositoryIssues('open').catch(() => []), listRepositoryIssues('closed').catch(() => []), listRepositoryCommits().catch(() => [])]); return { latestIssues, openIssues, closedIssues, recentCommits, relationships: latestIssues.map((issue) => ({ proposal: issue.source_id, issue: issue.github_issue_url ?? `#${issue.github_issue_number}`, prompt: issue.proposal_source ? 'Generated' : 'Missing', commit: recentCommits.find((commit) => commit.message.includes(`#${issue.github_issue_number}`) || commit.message.includes(issue.source_id))?.html_url ?? null, deployment: null })) }; }
function recommendationFor(id: string) { return ({ 'empty-sections': 'Add explicit empty-state components that explain what real data is missing and how to add it.', 'repeated-sync-failures': 'Group failed sync diagnostics by account/service and show the next recovery action.', 'low-command-confidence': 'Add parse confidence history, examples, and safer clarification thresholds.', 'too-many-cancellations': 'Capture cancellation reasons and surface plan-quality trends.', 'health-structure': 'Expand health log schema/UI with severity, duration, trigger, medication, and follow-up fields.', 'google-project-links': 'Add a review queue for Google signals and project-link correction actions.', 'static-memory-risk': 'Replace static memory counts with persisted database/API counts or label them clearly as stored seed memory.' } as Record<string, string>)[id] ?? 'Improve the related system area using only real stored data.'; }
function impactFor(severity: SystemWeakness['severity']) { return severity === 'high' ? 'High: safer decisions and fewer failed workflows.' : severity === 'medium' ? 'Medium: better trust and less manual review.' : 'Low: clearer expectations and less confusion.'; }
function buildCodexPrompt(weakness: SystemWeakness, plan: EngineeringPlan) { return `You are implementing a human-approved Shaikh OS improvement. Do not auto-merge, auto-deploy, modify environment variables, or perform destructive database changes.\n\nIssue summary: ${weakness.title} — ${weakness.detail}\nEvidence: ${weakness.evidence.join('; ')}\nMetrics: ${weakness.metrics.map((metric) => `${metric.label}: ${metric.value}${metric.total ? `/${metric.total}` : ''} (${metric.detail})`).join('; ')}\nConfidence: ${weakness.confidenceScore}%\nReasoning: ${weakness.reasoningChain.join(' -> ')}\nAffected files: ${plan.affectedFiles.join(', ')}\nDatabase changes: ${plan.databaseChanges.join('; ')}\nUI changes: ${plan.uiChanges.join('; ')}\nAcceptance criteria: evidence, metrics, confidence, reasoning, implementation plan, prompt, status, issue, commit, and deployment relationships remain visible; every execution stage requires human approval.\nTesting requirements: ${plan.testingRequirements.join('; ')}`; }

export async function persistAudit(snapshot: SystemAuditSnapshot) { await supabaseRequest('agent_system_audits', { method: 'POST', body: JSON.stringify({ snapshot, metrics: snapshot.metrics, weaknesses: snapshot.weaknesses, captured_at: snapshot.capturedAt }) }); if (snapshot.proposals.length) await supabaseRequest('agent_improvement_proposals?on_conflict=proposal_key', { method: 'POST', headers: { Prefer: 'resolution=merge-duplicates,return=representation' }, body: JSON.stringify(snapshot.proposals.map((proposal) => ({ proposal_key: proposal.id, observation: proposal.observation, problem: proposal.problem, evidence: proposal.evidence, metrics: proposal.metrics, confidence_score: proposal.confidenceScore, reasoning_chain: proposal.reasoningChain, recommendation: proposal.recommendation, expected_impact: proposal.expectedImpact, risk_level: proposal.riskLevel, implementation_complexity: proposal.complexity, engineering_plan: proposal.engineeringPlan, codex_prompt: proposal.codexPrompt, prompt_history: proposal.promptHistory, execution_status: proposal.executionStatus, status: proposal.status }))) }); }
export async function saveProposalFeedback(proposalKey: string, feedbackType: ImprovementProposal['status']) { const executionStatus = feedbackType === 'approved' ? 'Approved' : 'Proposed'; await supabaseRequest('agent_feedback', { method: 'POST', body: JSON.stringify({ proposal_key: proposalKey, feedback_type: feedbackType, raw_feedback: `Improvement proposal marked ${feedbackType}`, correction: { proposal_key: proposalKey, feedback_type: feedbackType } }) }); await supabaseRequest(`agent_improvement_proposals?proposal_key=eq.${encodeURIComponent(proposalKey)}`, { method: 'PATCH', body: JSON.stringify({ status: feedbackType, execution_status: executionStatus, updated_at: new Date().toISOString() }) }); }
